<?php /** @var $block \GhoSter\ChangeCustomerPassword\Block\Adminhtml\Customer\PasswordChange */?>

<?php if ($customerId = $block->getCustomerId()): ?>
<div class="change-customer-pwd fieldset-wrapper">
    <div class="fieldset-wrapper-title">
        <strong class="title">
            <span><?= /* @escapeNotVerified */ $block->escapeHtml(__('Change Password')); ?></span>
        </strong>
    </div>

    <div class="admin__fieldset-wrapper-content">
        <form action="<?= $block->escapeUrl($block->getUrl('customer/password/changePwdPost')); ?>"
              method="post"
              data-mage-init='{"validation": {}}'>
            <?= $block->getBlockHtml('formkey') ?>
        <input id="customer_id" type="hidden" name="customer_id" value="<?= $block->escapeHtml($customerId); ?>" />
            <div class="admin__field admin__field-medium">
                <label class="admin__field-label">
                    <span><?= /* @escapeNotVerified */ $block->escapeHtml(__('Enter Password')); ?></span>
                </label>
                <div class="admin__field-control">
                    <input class="admin__control-text"
                           type="password"
                           aria-label="<?= $block->escapeHtml(__('Password')) ?>"
                           name="new_customer_pwd"
                           data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                           data-password-min-character-sets="<?= $block->escapeHtmlAttr(
                                   $block->getRequiredCharacterClassesNumber()
                           ) ?>"
                           data-validate="{required:true, 'validate-customer-password':true}"
                           autocomplete="off"
                           title="<?= $block->escapeHtml(__('Password')) ?>"
                           placeholder="<?= $block->escapeHtml(__('Password')) ?>">
                </div>
            </div>

            <div class="admin__field admin__field-control action">
                <button id="save"
                        title="<?= $block->escapeHtml(__('Save Customer')) ?>"
                        type="submit"
                        class="action-scalable
                        save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"
                        data-form-role="save"
                        data-ui-id="save-button"
                        role="button"
                        aria-disabled="false">
                    <span class="ui-button-text">
                        <span><?= /* @escapeNotVerified */ $block->escapeHtml(__('Update Password')); ?></span>
                    </span>
                </button>
            </div>
        </form>
    </div>
</div>
<?php endif; ?>
