<?php /** @var $block \GhoSter\ChangeCustomerPassword\Block\Adminhtml\Customer\PasswordChange */?>

<?php if($customerId = $block->getCustomerId()): ?>
    <div class="fieldset-wrapper-title">
        <strong class="title">
            <span><?php /* @escapeNotVerified */ echo __('Change Password'); ?></span>
        </strong>
    </div>

    <div class="admin__fieldset-wrapper-content">
        <form action="<?php echo $block->getUrl('customer/password/change'); ?>" method="post">
        <?php echo $this->getBlockHtml('formkey')?>
        <input id="customer_id" type="hidden" name="customer_id" value="<?php echo $customerId; ?>" />
            <div class="admin__field">
                <label class="admin__field-label">
                    <span><?php /* @escapeNotVerified */ echo __('Enter Password'); ?></span>
                </label>
            </div>
            <div class="admin__field-control">
                <input class="admin__control-text" type="password" aria-label="Password" name="new_customer_pwd" style="width: 48%" title="">
            </div>

            <div class="admin__field-control action">
                <button id="save" title="Save Customer" type="submit" class="action- scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" data-form-role="save" data-ui-id="save-button" role="button" aria-disabled="false">
                    <span class="ui-button-text">
                        <span><?php /* @escapeNotVerified */ echo __('Update Password'); ?></span>
                    </span>
                </button>
            </div>
        </form>
    </div>
<?php endif; ?>